name: Documentation Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  documentation:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
      - name: Prerequisites
        run: |
          apt-get update
          apt-get install -y git doxygen graphviz
        shell: bash

      - name:  Checkout Code
        uses:  actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Execute script to build our documentation and update pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github
          ./build_docs_on_github.sh
        shell: bash