name: Documentation Build
# execute for every push no matter which branch
on:
  push:
 
jobs:
 
  documentation:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
 
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git doxygen graphviz
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash
 
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       cd hector_math
       docs/build_docs.sh
      shell: bash
